tmm1/test-queue

lib/test_queue/runner.rb

I'm not exactly sure what happened but it seems there's a case of empty slave message and it causes an exception.
The stack trace is here.
```
xxx/lib/test_queue/runner.rb:197:in `start_relay': undefined method `gsub!' for nil:NilClass (NoMethodError)
from xxx/lib/test_queue/runner.rb:159:in `execute_parallel'
from xxx/lib/test_queue/runner.rb:94:in `execute'
```
I think we should not `gsub` on `nil` value.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/tmm1/test-queue/19)

Fix empty slave message issue

---

Gemfile-rspec3-0
Gemfile-rspec3-0.lock
Gemfile-rspec3-1
Gemfile-rspec3-1.lock
Gemfile-rspec3-2
Gemfile-rspec3-2.lock
lib/test_queue/runner/rspec3.rb

RSpec 3.2 has [slightly changed how hooks are handled around the suite](https://github.com/rspec/rspec-core/commit/8232f61e0ba17b71dfd426eaf07da48ee2cad47e), and this has broken the test queue rspec runner:
```
$ for gemfile in Gemfile-rspec3-?; do echo $gemfile; BUNDLE_GEMFILE="$gemfile" bundle exec rspec-queue test/sample_spec.rb; done
Gemfile-rspec3-0
Starting test-queue master (/tmp/test_queue_95888_70258872569000.sock)
==> Starting test-queue worker [1] (96073 on Bumblebee.local) - iterating over /tmp/test_queue_95888_70258872569000.sock
RSpecSleep(1): .  <0.260>
RSpecSleep(4): .  <0.251>
RSpecSleep(25): .  <0.252>
RSpecSleep(5): .  <0.251>
RSpecSleep(15): .  <0.251>
RSpecSleep(26): .  <0.251>
RSpecSleep(7): .  <0.252>
RSpecFailure: F  <0.007>
Failures:
1) RSpecFailure fails …
```

RSpec 3.2 Fix

---

.gitignore
lib/test_queue/runner/cucumber.rb

In modern cucumber, @features_loader is an array.
Fix:
/.rvm/gems/ruby-2.2.2/gems/test-queue-0.2.13/lib/test_queue/runner/cucumber.rb:26:in `initialize': undefined method `features' for #<Array:0x007fbe64afa080> (NoMethodError)
Also I noticed something weird. If I use cucumber-queue on the [page-object](https://github.com/cheezy/page-object) repo, the [test time doubles](https://github.com/cheezy/page-object/issues/298#issuecomment-133977550). I was hoping test-queue would make the cucumbers faster.

Fix cucumber support

---

lib/test_queue/iterator.rb

This patch fixes a Ruby warning "assigned but unused variable".

⚠️ assigned but unused variable

---

lib/test_queue/runner.rb

This method is called on each iteration of the queue loop. Subclasses can override to add whatever behavior they need. For instance, you could record metrics about how many remote workers have connected. Or you could abort the build if not enough workers connect.
I also added an `abort` method to let subclasses cleanly abort a test run.
This replaces #33; subclasses can implement that behavior using this new callback if they choose.
/cc @bhuga @tmm1

Add TestQueue::Runner#queue_status

---

lib/test_queue/runner.rb

When true, we `exit!` when `#execute` completes. When false, we just return the number of failures from `#execute` to allow the caller to decide what to do. Defaults to true to maintain previous behavior.
/cc @bhuga

Add TestQueue::Runner#exit_when_done

---

bin/minitest-queue
bin/testunit-queue

The README suggests running `minitest-queue` via `minitest-queue $(find test/
-name \*_test.rb)`. This command fails with:
> minitest-queue:4:in `require': cannot load such file -- test//blah_test.rb (LoadError)
The issue is that the argument does not have the relative path specifier `./`
prefixing the filename. The fix passes the absolute_path to the file. This fix
also works if the absolute path is already given.
This commit also fixes the same issue for `testunit-queue`.

Use absolute_path for require in minitest-queue.

---

README.md
lib/test_queue/iterator.rb
lib/test_queue/runner.rb
lib/test_queue/runner/rspec.rb
lib/test_queue/runner/rspec3.rb

Add SPLIT_GROUPS env option for rspec tests to split example groups to run individual examples off of the queue.

Add option to split example groups to individual examples for rspec

---

README.md

A gem version badge is nice to have in the readme so people can easily see the most recently released version.

Add gem badge

---

lib/test_queue/iterator.rb
lib/test_queue/runner.rb
lib/test_queue/runner/minitest4.rb
lib/test_queue/runner/minitest5.rb
lib/test_queue/runner/rspec.rb
lib/test_queue/runner/testunit.rb

This allows builds to optionally be halted early if any worker encounters abnormal numbers of test failures.
The number of failures to halt at is defined in the `TEST_QUEUE_EARLY_FAILURE_LIMIT` environment variable; if defined, at the end of each suite, the worker will compare the number of failures it's encountered to date via that number. If it hits the limit, the worker immediately halts itself and notifies master with the new `KABOOM` command; if master encounters `KABOOM`, it stops distributing jobs and reaps all of the workers immediately without waiting for completion, then prints the results.
This can be useful for very large test suites; for example, if a CI system is regularly testing branches which can take multiple minutes to complete, it can be helpful for it to be able to …

Enable fast failures

---

lib/test_queue/runner.rb
test/minitest5.bats

I don't think this is useful at all for test-queue users. It has some small utility for test-queue developers, but it's pretty easy to debug things with `TEST_QUEUE_WORKERS=1`. This mode is buggy in at least one way: it doesn't set the exit code correctly.
So, this is essentially unused/unnecessary code and could be removed on that basis alone. But it also happens to be making it harder to make another change I'm working on: making the test-queue master not `require` any test files and making the workers only `require` the test files they need, which helps with startup latency in very large test suites.
/cc @tmm1 @bhuga

Remove TEST_QUEUE_WORKERS=0 support

---

lib/test_queue/runner.rb

If the code invoking test-queue also forks its own subprocesses, we could steal their termination status via our `Process.waitpid(-1)` call. Now we only listen for termination of our own workers' PIDs.
The change in the structure of the code also means that we call `waitpid` for every worker on every iteration of the `distribute_queue` loop. With 8 workers, this is about 6-7x more expensive in a microbenchmark (1 microsecond for `Process.waitpid(-1)` vs. 7 microseconds for `Process.waitpid(pid)` in a loop), but should still be dwarfed by time spent actually running the tests.
I also have plans for making the test-queue master fork off another utility process, and this change will help with that one.
/cc @bhuga @tmm1

Only wait for our own workers' PIDs

---

lib/test_queue/runner/rspec.rb
lib/test_queue/runner/rspec2.rb
test/rspec.bats
test/samples/sample_split_spec.rb

Using TEST_QUEUE_SPLIT_GROUPS currently raises an exception:
```shellsession
$ TEST_QUEUE_SPLIT_GROUPS=true bundle exec rspec-queue test/samples/sample_spec.rb 
/Users/aroben/dev/test-queue/lib/test_queue/runner/rspec.rb:33:in `block in initialize': undefined method `id' for #<RSpec::Core::Example:0x007fb42a205bd0> (NoMethodError)
from /Users/aroben/dev/test-queue/lib/test_queue/runner/rspec.rb:33:in `each'
from /Users/aroben/dev/test-queue/lib/test_queue/runner/rspec.rb:33:in `sort_by'
from /Users/aroben/dev/test-queue/lib/test_queue/runner/rspec.rb:33:in `sort_by!'
from /Users/aroben/dev/test-queue/lib/test_queue/runner/rspec.rb:33:in `initialize'
from /Users/aroben/dev/test-queue/bin/rspec-queue:4:in `new'
from /Users/aroben/dev/test-queue/bin/rspec-queue:4:in `<top (required)>'
from …
```

Fix TEST_QUEUE_SPLIT_GROUPS

---

test/minitest5.bats

In these tests, only a single test fails. That failing test could be run
on either the central master or the remote master. But regardless of
which master it runs on, the central master should fail, so that's the
process whose exit code we should be testing.
Note that the remote master now starts up first. It shouldn't matter
which master starts first (and ideally we'd have tests for both orders)
and doing it this way keeps the test easier to read.
/cc #43 @bhuga

Test the central master's exit code, not the remote master's

---

.travis.yml
lib/test_queue/iterator.rb
lib/test_queue/runner.rb
lib/test_queue/runner/cucumber.rb
lib/test_queue/runner/minitest.rb
lib/test_queue/runner/minitest4.rb
lib/test_queue/runner/minitest5.rb
lib/test_queue/runner/rspec.rb
lib/test_queue/runner/sample.rb
lib/test_queue/runner/testunit.rb
lib/test_queue/stats.rb
script/cibuild
script/spec
spec/stats_spec.rb

Without this, .test_queue_stats grows without bound as a project's tests
evolve. New suites get added but old ones never get removed.
The stats file is now managed by a TestQueue::Stats class. Each suite is
reprsented by a TestQueue::Stats::Suite value object. I added some
simple specs that Travis will run.
The format of the stats file has changed. Old stats will be ignored and
overwritten with new-format stats.
/cc @tmm1 @bhuga

Prune suites not seen in 8 days from .test_queue_stats

---

test/rspec.bats
test/samples/sample_split_spec.rb
test/testlib.bash

We now use a single group containing two slow examples. When split, we should end up with one example per worker.
/cc @bhuga

Make TEST_QUEUE_SPLIT_GROUPS test more deterministic

---

bin/minitest-queue
bin/testunit-queue
lib/test_queue/iterator.rb
lib/test_queue/runner.rb
lib/test_queue/runner/cucumber.rb
lib/test_queue/runner/minitest4.rb
lib/test_queue/runner/minitest5.rb
lib/test_queue/runner/rspec.rb
lib/test_queue/runner/rspec2.rb
lib/test_queue/runner/rspec3.rb
lib/test_queue/runner/testunit.rb
lib/test_queue/stats.rb
lib/test_queue/test_framework.rb
spec/stats_spec.rb
test/cucumber.bats
test/minitest5.bats
test/testlib.bash

For large test suites, having the master require all test files can introduce tens of seconds of latency before any tests start running at all. Since each worker only runs a subset of the tests, it's wasteful to make them all wait until all tests have been loaded.
First, some terminology:
- a "suite" is the unit of work that test-queue parallelizes. (E.g., in Minitest this is a test class. In RSpec this is an ExampleGroup, unless `TEST_QUEUE_SPLIT_GROUPS` is being used.)
- a "suite name" is a string that uniquely identifies a suite, and is stable across multiple processes that each load that suite separately
The master no longer loads any suites. It forks a "suite discovery" process that loads all the suite files specified by the test framework (usually based on command line parameters). …

Require test files in workers instead of master

---

lib/test_queue/runner.rb
test/minitest5.bats
test/testlib.bash

`TEST_QUEUE_FORCE` is supposed to specify both the list of suites to run and the order they are run in. Currently, order is only guaranteed if `.test_queue_stats` contains all the specified suites. This PR will fix this (but right now just adds a failing test to demonstrate the bug).
/cc @bhuga

Always respect TEST_QUEUE_FORCE ordering

---

lib/test_queue/runner/rspec.rb
test/rspec.bats
test/samples/sample_rspec_helper.rb
test/samples/sample_shared_examples_for_spec.rb
test/samples/sample_use_shared_example1_spec.rb
test/samples/sample_use_shared_example2_spec.rb

Raise exception,  using the `require` via `shared_examples_for`.
Test:
```
@test "Use to Shared Exsamples." {
run bundle exec rspec-queue ./test/samples/sample_use_shared_example1_spec.rb \
./test/samples/sample_use_shared_example2_spec.rb
assert_status 0
}
```
Exception:
```
✗ Use to Shared Exsamples.
(from function `assert_status' in file test/testlib.bash, line 32,
in test file test/rspec.bats, line 43)
`assert_status 0' failed
Expected status to be 0 but was 1. Full output:
Starting test-queue master (/tmp/test_queue_88633_70198842389740.sock)
/Users/takeshinoda/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:347:in `find_and_eval_shared': Could not find shared examples "Sample Example" (ArgumentError)
from …
```

Fix the Shared examples beging deleting.

---

lib/test_queue/runner.rb

I'm using test-queue with rspec in master-slave distributed mode over several machines. I would like to collect structured data such as test coverage metrics from the worker processes on both the master and the slave machines and summarize them on the master machine to calculate a coverage rate.
I've found that it would be handy to piggyback such miscellaneous data on the `WORKER` messages sent from the slaves to the master. But there is not an appropriate Runner method to override in order to prepare such an additional payload relayed from slaves.
This patch extracts routines related to a master collecting test results from a worker process as a method, in order to allow subclasses of Runner to collect application-specific data.

Extract method for collecting worker result

---

Gemfile-cucumber1-3.lock
Gemfile-cucumber2-4.lock
Gemfile-minitest4.lock
Gemfile-minitest5.lock
Gemfile-rspec2-1.lock
Gemfile-rspec3-0.lock
Gemfile-rspec3-1.lock
Gemfile-rspec3-2.lock
Gemfile-testunit.lock
Gemfile.lock

The version was bumped in 71d4cb8ffbf8b7659da8fdd23961964ad941c794 in the gemfile but not in the lockfiles.
cc @aroben

Update test-queue version in Gemfiles.lock

---

lib/test_queue/iterator.rb
lib/test_queue/runner.rb

Currently, tokens are only verified when a slave first connects to master, not on every communication. In a scenario where the master process aborts a build, but the slave processes haven't been reaped, those slaves can end up communicating with a new master when a new build is commenced on the same host. This moves the run token to the start of the message and sends/checks it on every communication.
This is a pretty minimal change, and I think it would be good to refactor `distribute_queue` a little, but it should solve the immediate issue.
cc @aroben, @bhuga

Always send the token when communicating with the master

---

test/minitest5.bats
test/sleepy_runner.rb

The tests should fail here since they're missing the fix from #65. cc @aroben

Swap order of starting up RELAY/SOCKET processes in multi-master tests

---

lib/test_queue/runner.rb
test/minitest5.bats
test/sleepy_runner.rb

A stray space in the `/^SLAVE` regex meant that certain commands were being ignored. I've also added logging when a command doesn't match any of the regexes and will be ignored, though I think there's an argument to be made for replying with a more explicit error to the worker.
cc @aroben

Fix SLAVE regex, log unrecognized commands

---

lib/test_queue/stats.rb

`Marshal.load` can raise `ArgumentError` when given malformed data; in these cases, we'll want to rescue like with the other error conditions.
cc @aroben

Stats: rescue ArgumentError when loading stats file

---

lib/test_queue/runner.rb

Ruby 2.3.1 says `File.exists?` is deprecated, and use `File.exist?` instead as follows, and `File.exist?` has also existed since Ruby 1.8.x, or before.
```
ruby/2.3.0/gems/test-queue-0.4.0/lib/test_queue/runner.rb:396: warning: File.exists? is a deprecated name, use File.exist? instead
ruby/2.3.0/gems/test-queue-0.4.0/lib/test_queue/runner.rb:401: warning: File.exists? is a deprecated name, use File.exist? instead
```

Replace File.exists? with File.exist? for deprecation warning.

---

lib/test_queue/runner.rb

Ruby 2.3.1 says @aborting is not initialized as follows, so I've fixed it.
```
ruby/2.3.0/gems/test-queue-0.4.0/lib/test_queue/runner.rb:408: warning: instance variable @aborting not initialized
```

Suppress @aborting is not initialized warning.

---

lib/test_queue/iterator.rb
lib/test_queue/runner.rb

This is adapted from a couple of commits in @aroben's suite-files branch. This is definitely still broken, opening a PR to compare cibuild results to my local runs.
1. ~~In the "rename" test, the queue passed when `Runner` is instantiated at the beginning of the second test run contains both the old and new suite names, both associated with the same path. The old suite names are flagged as discovered-but-not-run.~~
2. ~~A couple of the rspec examples are broken, possibly due to example splitting.~~

WIP Report unexpected tests, discovered-but-unrun tests

---

lib/test_queue/runner.rb
test/minitest5.bats
test/samples/sample_minitest5.rb

Workers missing an exit status are an error. This can happen if a worker's process is killed out-of-band. Currently, summarize will explode on the `%` call if any of these values are nil. 
This doesn't seem too tough to write a test for, but I'm not sure where to put it. Should we copy one of the suites, say minitest5, and have a suite for test-queue features as opposed to end-to-end tests for each test framework?

Use an error status instead of nil if we're missing a worker status code

---

README.md
lib/test_queue/runner.rb
test/minitest5.bats

Distributed builds use a single central master and one or more remote masters. All masters have workers. We no longer call anything a "slave", which is both problematic on its own and could be confusing as to whether it referred to a remote master or a worker.
This is a breaking change.

Clean up and improve terminology around distributed builds

---

lib/test_queue/runner/rspec.rb
lib/test_queue/runner/rspec2.rb
lib/test_queue/runner/rspec3.rb

Hi. 
When use rspec3, show warning message such as followings. Fix it.
```
Treating `metadata[:execution_result]` as a hash is deprecated. Use the attributes methods to access thedata instead. Called from /Users/w1mvy/src/github.com/w1mvy/test-queue/lib/test_queue/runner/rspec.rb:15:in `block in failure_count'.
```
Show this warning, when use  rspec option `config.raise_errors_for_deprecations!`.
```
The `:example_group` key in an example group's metadata hash is deprecated. Use the example group's hashdirectly for the computed keys and `:parent_example_group` to access the parent example group metadata instead. Called from /Users/w1mvy/src/github.com/w1mvy/test-queue/lib/test_queue/runner/rspec.rb:53:in `block in suites_from_file'.
```

Fix deprecated method at rspec3

---

test-queue.gemspec

This reduces unneeded redirection from `http://...` to `https://...` when someone visits this gem's homepage via https://rubygems.org/gems/test-queue.

GitHub is https by default

---

lib/test_queue/runner.rb

This PR suppresses the following Ruby's warning.
```console
/Users/koic/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/test-queue-0.4.2/lib/test_queue/runner.rb:299:
warning: instance variable @early_failure_limit not initialized
```

Suppress a Ruby's warning

---

test-queue.gemspec

`Gem::Specification#has_rdoc=` is a deprecated method.
This PR removes `Gem::Specification#has_rdoc=` from gemspec.
```console
% ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin17]
% gem -v
3.0.4
% cd path/to/test-queue
% bundle install
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It
will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from
/Users/koic/src/github.com/tmm1/test-queue/test-queue.gemspec:13.
Fetching gem metadata from https://rubygems.org/..........
(snip)
```

Remove `Gem::Specification#has_rdoc=` from gemspec

---

lib/test_queue/runner.rb

Follow up https://github.com/tmm1/test-queue/commit/cf65d12.
This PR prevents a breaking change when using deprecated `TEST_QUEUE_SLAVE_MESSAGE` environment variable.
It is user-friendly to provide a warning message instead of a sudden environment variable name change.

Prevent a breaking change when using deprecated env var

---

.github/workflows/test.yml

This PR fixes the following invalid workflow setting:
> The workflow is not valid. .github/workflows/test.yml (Line: 32, Col: 7):
> A sequence was not expected
https://github.com/tmm1/test-queue/actions/runs/2724097177/workflow
> Error: Error: $BUNDLE_GEMFILE is set to gemfiles/Gemfile but does not exist
https://github.com/tmm1/test-queue/runs/7481835451?check_suite_focus=true#step:3:27

Fix invalid workflow settings

---

.github/workflows/test.yml

It makes failed matrices identifiable by job name.

Add `matrix.gemfile` to GitHub Actions's job name

---

script/bootstrap

There is no need to keep a temporary directory.

Remove tmp dir no longer needed for bats installation

---

.gitignore

This PR adds the vendor directory where `script/bootstrap` installs `bats` to .gitignore:
```console
% script/bootstrap
++ dirname script/bootstrap
+ cd script/..
++ pwd
+ ROOT=/Users/koic/src/github.com/tmm1/test-queue
+ rm -rf tmp
+ mkdir tmp
+ mkdir -p vendor/bats
+ curl --silent --location --show-error https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz
+ tar -xz -C tmp
+ tmp/bats-0.4.0/install.sh /Users/koic/src/github.com/tmm1/test-queue/vendor/bats
Installed Bats to /Users/koic/src/github.com/tmm1/test-queue/vendor/bats/bin/bats
% ls vendor
bats
```
This vendor directory is not managed by the repository.

Add vendor dir to .gitignore

---

.github/workflows/test.yml
gemfiles/Gemfile-rspec3
gemfiles/Gemfile-rspec3-0
gemfiles/Gemfile-rspec3-1
gemfiles/Gemfile-rspec3-2
test/rspec.bats

Currently the latest RSpec is 3.12 so RSpec 3.0, 3.1, and 3.2 are quite old. This PR allows testing with new code in the RSpec 3 series.
```console
% vendor/bats/bin/bats test/rspec.bats
```
Also, since the output format of test results changed between RSpec 3.2 and 3.12, it is updating the test/rspec.bats tests.

Integrate RSpec 3 tests to the latest version

---

.github/workflows/test.yml

This PR dowangrades Ruby version from 3.1 to 3.0 to fix the following build error:
https://github.com/tmm1/test-queue/actions/runs/4354208063/jobs/7609496270

CI against Ruby 3.0

---

.github/workflows/test.yml
test-queue.gemspec

They have reached EOL and the test-queue wants to move forward without worrying about them. Ruby 2.7 will reach EOL in March 2023, but since it is the last version in the 2.x series, it will be put on hold for a while.

Drop Ruby 2.6 and lower support

---

exe/cucumber-queue
exe/minitest-queue
exe/rspec-queue
exe/testunit-queue
lib/test-queue.rb
lib/test_queue.rb
lib/test_queue/runner.rb
lib/test_queue/runner/minitest.rb
lib/test_queue/runner/minitest4.rb
lib/test_queue/runner/minitest5.rb
lib/test_queue/runner/puppet_lint.rb
lib/test_queue/runner/rspec.rb
lib/test_queue/runner/sample.rb
lib/test_queue/runner/testunit.rb
spec/stats_spec.rb
test/sleepy_runner.rb

`require_relative` should be used if the file paths are relative to improve a bit of performance. Or add the `lib` directory to `$LOAD_PATH` so that `require` finds it first.

Use `require_relative`

---

.github/workflows/test.yml
gemfiles/cucumber1_3.gemfile
gemfiles/cucumber2_4.gemfile
gemfiles/minitest4.gemfile
gemfiles/minitest5.gemfile
gemfiles/rspec2.gemfile
gemfiles/rspec3.gemfile
gemfiles/testunit.gemfile

This PR splits CI matrix by Bats. Not all matrices need to be executed all the time. It is enough for Bats per testing framework to run.

Split CI matrix by Bats

---

.github/workflows/test.yml
Appraisals
gemfiles/rspec2.gemfile

That's what was changed in Ruby 3.2 to make CI work.
RSpec 2 has separate job because RSpec 2 doesn't work with Ruby 3.2:
```console
in `block in find_first_parent_containing': undefined method `exists?' for File:Class (NoMethodError)
#
in `block in ascend_until'
```
https://github.com/tmm1/test-queue/actions/runs/4443269714/jobs/7800375435
So RSpec 2 is the last version Ruby 3.1 worked on. This PR updates out-of-development RSpec 2 to 2.99.
And the value of `BUNDLE_GEMFILE: ${{ matrix.gemfile }}` is empty in Ruby 3.2:
```console
Run bundle exec appraisal minitest5 bundle install
bundle exec appraisal minitest5 bundle install
shell: /usr/bin/bash -e {0}
env:
BUNDLE_GEMFILE:
TEST_QUEUE_WORKERS: 2
TEST_QUEUE_VERBOSE: 1
/opt/hostedtoolcache/Ruby/3.2.1/x64/lib/ruby/3.2.0/bundler/resolver.rb:29 …
```

CI against Ruby 3.2

---

.github/workflows/test.yml
lib/test_queue/runner/rspec.rb
test/rspec2.bats
test/rspec3.bats

Requrie a target target directory:
```console
$ bundle exec test-queue spec
```
If the `spec` path is omitted, user might be surprised to see 0 test runs.
`spec` directory is target by default when target directory is ommited:
```console
$ bundle exec test-queue
```
So, user can use it in the same abbreviated way as RSpec.
```console
$ bundle exec rspec # spec directory by default target.
```
Note, however, that this PR implementation (i.e. `@files_or_directories_to_run`) is naive as it relies on: https://github.com/rspec/rspec-core/blob/v3.12.1/lib/rspec/core/configuration.rb#L1061-L1077

Run with `spec` directory by default for `rspec-queue` command

---

Appraisals
gemfiles/minitest5.gemfile
test/minitest5.bats

Pass tests up to Minitest 5.10 by making `MiniTestSleepXx` an early number. It may be related to sleep time.
```console
$ TEST_QUEUE_VERBOSE=1 TEST_QUEUE_WORKERS=2 bundle exec appraisal minitest5 vendor/bats/bin/bats test/minitest5.bats
```
On the other hand, 5.11 does not pass the E2E test due to something below. Further investigation is required. https://github.com/minitest/minitest/compare/v5.10.3..v5.11.0

Pin Minitest 5.10.0 for E2E testing

---

lib/test_queue/runner/minitest5.rb

This PR fixes the following error when running `minitest-queue`:
```console
$ bundle exec minitest-queue test/**/*.rb
bundler: failed to load command: minitest-queue (/Users/koic/.rbenv/versions/3.2.1/bin/minitest-queue)
/Users/koic/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/minitest-5.18.0/lib/minitest/test.rb:74:in `srand': no implicit conversion of nil into Integer (TypeError)
srand Minitest.seed
^^^^^^^^^^^^^
from /Users/koic/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/minitest-5.18.0/lib/minitest/test.rb:74:in `runnable_methods'
from /Users/koic/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/test-queue-0.5.0/lib/test_queue/runner/minitest5.rb:59:in `block in initialize'
from /Users/koic/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/test-queue-0.5.0/lib/test_queue/runner/minite …
```

Fix an error for `minitest-queue`

---

lib/test_queue/iterator.rb
lib/test_queue/runner.rb

It does not expect to multiline regexp matching.

Use `\A` for socket command matching

---

lib/test_queue/runner/minitest5.rb
test/minitest5.bats

Resolves #30.
This PR makes `Runner::MiniTest` display seed value when running Minitest 5 This new feature will not be added to Minitest 4 as MT4 support will be dropped soon.
```console
$ bundle exec minitest-queue test/**/*_test.rb
Starting test-queue master (/tmp/test_queue_42080_1560.sock)
==> Summary (16 workers in 4.0841s)
(snip)
```
```console
$ bundle exec minitest-queue test/**/*_test.rb
Run options: --seed 36048
Starting test-queue master (/tmp/test_queue_42080_1560.sock)
==> Summary (16 workers in 4.0841s)
(snip)
```

Display seed value when running Minitest 5

---

README.md
exe/minitest-queue
lib/test_queue/runner/minitest.rb
lib/test_queue/runner/minitest4.rb
lib/test_queue/runner/minitest5.rb
test/examples/example_minitest4.rb
test/examples/example_minitest5.rb
test/minitest4.bats
test/minitest5.bats
test/sleepy_runner.rb

Follow up https://github.com/minitest/minitest/commit/9a57c520
This PR renames `TestQueue::MiniTest::Runner` to  `TestQueue::Minitest::Runner` and `TestQueue::MiniTest::TestFramework` to `TestQueue::Minitest::TestFramework`.
For compatibility with 0.7 and earlier, it is also available in `TestQueue::MiniTest::Runner` and `TestQueue::MiniTest::TestFramework`.

Rename `MiniTest` to `Minitest`

---

lib/test_queue/version.rb
test-queue.gemspec

This PR extracts version of test-queue from gemspec to module constant. It is general gem structure.

Extract version of test-queue from gemspec to module constant

---

test-queue.gemspec

It reduces the distribution size by removing unnecessary test code, CI configure, and others at runtime.

Downsize distribution resources

---

lib/test_queue/runner/example.rb

This PR fixes the following error for lib/test-queue/runner/example.rb:
```console
$ bundle exec ruby lib/test_queue/runner/example.rb
/Users/koic/src/github.com/tmm1/test-queue/lib/test_queue/runner.rb:58:
in `initialize': undefined method `all_suite_files' for [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]:Array (NoMethodError)
all_files = @test_framework.all_suite_files.to_set
^^^^^^^^^^^^^^^^
from lib/test_queue/runner/example.rb:35:in `new'
from lib/test_queue/runner/example.rb:35:in `<main>'
```
Implemented to keep `TestQueue::Runner::Example.new(Array(1..10)).execute` in the runner/example.rb.

Fix an error for runner/example.rb

---

.gitignore
Rakefile
bin/console
bin/setup

This PR adds `bin/console` and moves `script/bootstrap` to `bin/setup`, both of which are development scripts.

Gather development scripts into `bin` directory

---

lib/test_queue/runner.rb

This PR removes deprecated `TEST_QUEUE_SLAVE_MESSAGE` environment variable.
The 0.5.0 release that deprecated it is in July 2022: https://github.com/tmm1/test-queue/releases/tag/v0.5.0
But it wouldn't be a bad time to remove it given the impact.

Remove deprecated `TEST_QUEUE_SLAVE_MESSAGE` environment variable

---

lib/test_queue/runner/rspec.rb
test/rspec3.bats
test/rspec4.bats

Issue solving similar to #113.
This PR makes `Runner::RSpec` display seed value when running RSpec.
```console
$ bundle exec rspec-queue
Starting test-queue master (/tmp/test_queue_42080_1560.sock)
==> Summary (16 workers in 4.0841s)
(snip)
```
```console
$ bundle exec rspec-queue
Randomized with seed 27022
Starting test-queue master (/tmp/test_queue_42080_1560.sock)
==> Summary (16 workers in 4.0841s)
(snip)
```

Display seed value when running RSpec

---

lib/test_queue/runner.rb
test/examples/example_testunit.rb

test_queue fails when bytesize of `suite_name` is 5.
Because marshal data includes "\n".
```ruby
require 'test/unit'
class Aiueo < Test::Unit::TestCase
def test_ok
assert true
end
end
```
```console
$ exe/testunit-queue t.rb
Starting test-queue master (/tmp/test_queue_98954_380.sock)
<internal:marshal>:34:in `load': marshal data too short (ArgumentError)
from /.../lib/test_queue/runner.rb:511:in `distribute_queue'
from /.../lib/test_queue/runner.rb:228:in `execute_internal'
from /.../lib/test_queue/runner.rb:119:in `execute'
from exe/testunit-queue:9:in `<main>'
```

Fix marshal load error when marshal data includes "\n"

---

lib/test_queue/runner/testunit.rb
test/examples/example_testunit_split.rb
test/testunit.bats

This PR add split groups feature to test-unit runner, and fix error on nested sub_test_cases.
Current version of testunit-queue fails when nested sub_test_cases exists.
```ruby
require 'test/unit'
class NestedTestCase < Test::Unit::TestCase
sub_test_case 'sub_test_case 1' do
test 'test 1' do
assert true
end
end
end
```
```console
$ TEST_QUEUE_WORKERS=1 testunit-queue test/examples/example_testunit_split.rb
Starting test-queue master (/tmp/test_queue_96944_460.sock)
==> Starting test-queue worker [1] (96960 on mini2023.local) - iterating over /tmp/test_queue_96944_460.sock
Loaded suite specified by test-queue master
Started
Finished in 0.103876 seconds.
-------------------------------------------------------------------------------
1 tests, 1 assertions, 0 failures, 0 errors, 0 pendings, 0 …
```

Add TEST_QUEUE_SPLIT_GROUPS feature to testunit runner

---

lib/test_queue/runner.rb

to make it easier to override the default behaviour of fork
if needed.
SimpleCov, for example, does this when [working with subprocesses](https://github.com/simplecov-ruby/simplecov?tab=readme-ov-file#running-simplecov-against-subprocesses).
> SimpleCov.enable_for_subprocesses will allow SimpleCov to observe subprocesses starting using Process.fork. This modifies ruby's core Process.fork method so that SimpleCov can see into it...

Use Process::fork in place of fork

---

.github/workflows/test.yml

https://github.com/ruby/setup-ruby/pull/553 has been merged.

Use Ruby 3.3 in the latest version of CI
